kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "nodejs-ex-pipeline"
spec:
  strategy:
    jenkinsPipelineStrategy:
        jenkinsfile: |-
          node('nodejs') {
             stage('build') {
                 openshiftBuild(buildConfig: 'nodejs-ex', showBuildLogs: 'true')
             }
             stage('deployDev') {
                 openshiftDeploy(deploymentConfig: 'nodejs-ex')
             }
             stage('deploySys') {
                 openshiftDeploy(deploymentConfig: 'nodejs-ex', namespace: 'nodejs-ex-sys')
             }
          }
