kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "nodejs-ex-pipeline"
spec:
  strategy:
    jenkinsPipelineStrategy:
        jenkinsfile: "node('nodejs') {\n  stage 'build'\n  openshiftBuild(buildConfig: 'nodejs-ex', showBuildLogs: 'true')\n  stage 'deployDev'\n  openshiftDeploy(deploymentConfig: 'nodejs-ex', nameSpace: 'dev')\n  stage 'deploySys'\n  openshiftDeploy(deploymentConfig: 'nodejs-ex', nameSpace: 'sys')}\n"
